// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uddhbmzlmrzrylfriplf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZGhibXpsbXJ6cnlsZnJpcGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTk2NzEsImV4cCI6MjA2OTYzNTY3MX0.ARRRtAwMTsomL6xuyBJ3XtHPuy559LnxxjjxSmDtkEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);